### ISSUE TITLE
Add new devices after initialization. 

### ISSUE THREAD

**Issue by jaretburkett** [dsandor/fauxmojs#3]
Is there a way to publish new devices on the fly? I tried destroying the instance and reinitialize it with new devices, but it kicks out a "throw new Error('Socket is already bound');" error. Currently, the only way I can find is restarting the application entirely.

**Comment by dsandor** [comment]
Can you share some of your code?  My guess is you are creating new instances of the FauxMo class when you add a new device. 

That won't work because it will try to create a new set of SSDP services.

We could add in some code to allow the devices configuration to be appended to after initialization.

**Comment by dsandor** [comment]
@jaretburkett can you check and see if the code @neophob just updated fixes your issue?
